// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUl4JA1tvbKtG0grzBHnsqd-Mqxsy3BCw',
    appId: '1:537551574861:web:b342d52f7a7cf06d6b0904',
    messagingSenderId: '537551574861',
    projectId: 'chat-app-958e6',
    authDomain: 'chat-app-958e6.firebaseapp.com',
    storageBucket: 'chat-app-958e6.firebasestorage.app',
    measurementId: 'G-7CJ17C1T55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbSy1POvwBghEar1ttlMqI1F7nq7-_EG4',
    appId: '1:537551574861:android:01664a4847dfdf426b0904',
    messagingSenderId: '537551574861',
    projectId: 'chat-app-958e6',
    storageBucket: 'chat-app-958e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC22ef30SvkpC3fLiLSY2lwGzdog4ngibo',
    appId: '1:537551574861:ios:0e2a14bc7ad1f3dd6b0904',
    messagingSenderId: '537551574861',
    projectId: 'chat-app-958e6',
    storageBucket: 'chat-app-958e6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC22ef30SvkpC3fLiLSY2lwGzdog4ngibo',
    appId: '1:537551574861:ios:0e2a14bc7ad1f3dd6b0904',
    messagingSenderId: '537551574861',
    projectId: 'chat-app-958e6',
    storageBucket: 'chat-app-958e6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUl4JA1tvbKtG0grzBHnsqd-Mqxsy3BCw',
    appId: '1:537551574861:web:606ea5ce2aca8c366b0904',
    messagingSenderId: '537551574861',
    projectId: 'chat-app-958e6',
    authDomain: 'chat-app-958e6.firebaseapp.com',
    storageBucket: 'chat-app-958e6.firebasestorage.app',
    measurementId: 'G-RX823E1Z8G',
  );
}
